### model
model_name_or_path: /data/models/DCLM-7B-8k-fp16

### method
finetuning_type: full

### dataset
task: mmlu_test # choices: [mmlu_test, ceval_validation, cmmlu_test]
template: fewshot
lang: en
n_shot: 5

### output
save_dir: saves/DCLM-7B-8k-fp16-20240806/eval_ck

### eval
batch_size: 1
