### model
model_name_or_path: /data/models/gemma2-2b-it
resume_from_checkpoint: saves/gemma2-2b-it-20240801/full/sft/checkpoint-5000

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: /data/configs/ds_config.json

### dataset
dataset: ihandy_20240701_fix
dataset_dir: /data/datasets/yx_test
template: gemma
cutoff_len: 4096
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/gemma2-2b-it-20240801/full/sft
logging_steps: 10
save_steps: 5000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 5.0e-5
num_train_epochs: 6.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
