### model
model_name_or_path: /opt/services/LLaMA-Factory-main/saves/alpaca_test

### method
finetuning_type: full

### dataset
task: mmlu_test # choices: [mmlu_test, ceval_validation, cmmlu_test]
template: fewshot
lang: en
n_shot: 5

### output
save_dir: saves/llama3.1-8b-it-alpaca_test/eval_ck

### eval
batch_size: 2
