### model
model_name_or_path: /opt/services/yx_test/llama-factory-new/saves/llama3.1-8b-origin-20240801/full/sft/checkpoint-3000

### method
finetuning_type: full

### dataset
task: mmlu_test # choices: [mmlu_test, ceval_validation, cmmlu_test]
template: fewshot
lang: en
n_shot: 5

### output
save_dir: /opt/services/yx_test/llama-factory-new/saves/llama3.1-8b-origin-20240801/eval_3000

### eval
batch_size: 2
