### model
model_name_or_path: /opt/services/yx_test/llama-factory-new/saves/Phi-3.5-MoE-instruct-20240829/full/sft

### method
finetuning_type: full

### dataset
task: mmlu_test # choices: [mmlu_test, ceval_validation, cmmlu_test]
template: phi
lang: en
n_shot: 5

### output
save_dir: /opt/services/yx_test/llama-factory-new/saves/Phi-3.5-MoE-instruct-20240829/eval

### eval
batch_size: 2
