### model
model_name_or_path: /data/models/meta-llama/Llama-3.1-8B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: /data/configs/ds_config.json

### dataset
dataset: ihandy_test_3500
dataset_dir: /data/datasets/yx_test
template: llama3
cutoff_len: 4096
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /opt/services/yx_test/llama-factory-new/saves/llama3.1-8b-20241206/full/sft
logging_steps: 10
save_steps: 5000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 5.0e-5
num_train_epochs: 6.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
# use_unsloth: true
save_only_model: true
