### model
model_name_or_path: /data/models/meta-llama/Llama-3.2-3B-Instruct
# adapter_name_or_path

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_dropout: 0.3
lora_alpha: 16
lora_target:
  ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]

### dataset
dataset: mixed-rp
dataset_dir: /data/datasets/yx_test
template: llama3
cutoff_len: 8192
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 1

### output
output_dir: /opt/services/yx_test/llama-factory-new-grpo/saves/llama3.2-3b-202504010909/lora/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 2.0e-4
# num_train_epochs: 3.0
max_steps: 500
lr_scheduler_type: linear
warmup_steps: 5
bf16: true
ddp_timeout: 180000000
use_unsloth: true
weight_decay: 0.01
### eval
eval_dataset: ihandy_eval
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 50

report_to: ["tensorboard"]
