### model
model_name_or_path: /data/models/meta-llama/Llama-3.2-3B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: /data/configs/ds_config.json

### dataset
dataset: ihandy_test
dataset_dir: /data/datasets/yx_test
template: llama3
cutoff_len: 8192
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16

weight_decay: 0.01

### output
output_dir: /opt/services/yx_test/llama-factory-new-grpo/saves/llama3.2-3b-202502260652/full/sft
logging_steps: 10
save_strategy: epoch
# save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 6.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
# use_unsloth: true
save_only_model: true
### eval
eval_dataset: ihandy_eval
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 50

report_to: ["tensorboard"]
