### model
model_name_or_path: /data/models/microsoft/Phi-3.5-mini-instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: /data/configs/ds_config.json

### dataset
dataset: ihandy_test
dataset_dir: /data/datasets/yx_test
template: phi
cutoff_len: 8096
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /opt/services/yx_test/llama-factory-new/saves/Phi-3.5-mini-instruct-20241115/full/sft
logging_steps: 10
save_steps: 5000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 5.0e-5
num_train_epochs: 6.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
flash_attn: fa2
# use_unsloth: true
